### PR TITLE
Unambig

### PR DESCRIPTION
**Pull request by stschaef**

### CODE REVIEW

**Comment by maxsnew** [comment]
Is this ready? It's not building

**Comment by stschaef** [comment]
It should be ready. It's passing locally and I have no diffs from the remote. 

I think I may have accidentally re-run old workflows (on older commits) instead of on the head. Running again now to be sure

**Comment by maxsnew** [comment]
It's showing some error to do with opaque:
```
/home/runner/work/grammars-and-semantic-actions/grammars-and-semantic-actions/code/cubical/NFA/Regex/Combinators.agda:218,15-18
warning: -W[no]UnfoldTransparentName
The name _⊕_, mentioned by an unfolding clause, does not belong to
an opaque block. This has no effect.
when scope checking the declaration
  import NFA.Regex.Combinators as .#NFA.Regex.Combinators-13138820953506565994
make: *** [Makefile:16: quicktest] Error 1
```

**Comment by maxsnew** [comment]
Also, please give more descriptive names to your PRs. This PR also makes a huge change which is to make stuff opaque

**Comment by stschaef** [comment]
> It's showing some error to do with opaque:
> 
> ```
> /home/runner/work/grammars-and-semantic-actions/grammars-and-semantic-actions/code/cubical/NFA/Regex/Combinators.agda:218,15-18
> warning: -W[no]UnfoldTransparentName
> The name _⊕_, mentioned by an unfolding clause, does not belong to
> an opaque block. This has no effect.
> when scope checking the declaration
>   import NFA.Regex.Combinators as .#NFA.Regex.Combinators-13138820953506565994
> make: *** [Makefile:16: quicktest] Error 1
> ```

This error makes no sense though, as this definition is opaque. 

What I meant was that the CI ran on a commit before sum was made opaque, and I made the mistake of re-running that job rather than spawning a new one on the new commit. So I believe that the current commit will build and I'd been running the wrong job

**Comment by maxsnew** [comment]
Ok it's not erroring locally for me either so I'll merge

**Pull request merged**
